CREATE TABLE Students(
	SID		INTEGER		PRIMARY KEY,
	Name		VARCHAR(20),
	gender		BOOLEAN,
	email		VARCHAR(100)
);

CREATE TABLE Projects(
	PID		INTEGER		PRIMARY KEY,
	Name		VARCHAR(20)
);

CREATE TABLE Teams(
	TID		INTEGER		PRIMARY KEY,
	LeaderID	INTEGER		UNIQUE		DEFAULT NULL,
	NoOfMembers	INTEGER,
	FOREIGN KEY (LeaderID)	REFERENCES Students(SID)
);

CREATE TABLE Members(
	SID		INTEGER,
	TID		INTEGER,
	dateJoined	DATE,
	role		VARCHAR(10),
	PRIMARY KEY(SID, TID),
	FOREIGN KEY (SID)	REFERENCES Students(SID),
	FOREIGN KEY (TID)	REFERENCES Teams(TID)
);

CREATE TABLE Demos(
	SID		INTEGER,
	TID		INTEGER,
	Date		DATE,
	time		time,
	grade		INTEGER,
	PRIMARY KEY(SID, TID),
	FOREIGN KEY (SID)	REFERENCES Students(SID),
	FOREIGN KEY (TID)	REFERENCES Teams(TID)
);
